#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /usr/share/nginx/html/index.html
service nginx start